# Generated by Django 3.2.3 on 2021-05-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='length',
            new_name='duration',
        ),
    ]
