# Generated by Django 3.2.3 on 2021-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
