# Generated by Django 3.2.7 on 2021-09-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_theme_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
