# Generated by Django 4.1.7 on 2023-03-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0009_video_search_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
