# Generated by Django 5.1.5 on 2025-02-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0011_video_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="language_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="view_count",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
