services:
  api:
    image: ${DOCKERHUB_USERNAME}/vj-api:${TAG:-latest}
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      # Application settings
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT:-8000}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

      # Django settings
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}

      # Database settings
      - POSTGRES_DB=${POSTGRES_DB}

      # CORS settings
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

      # Nginx proxy settings
      - SECURE_PROXY_SSL_HEADER=${SECURE_PROXY_SSL_HEADER}

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  static_volume:
