services:
  api:
    image: ${DOCKERHUB_USERNAME}/vj-api:${TAG:-latest}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - static_volume:/app/static

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  static_volume:
