services:
  db:
    container_name: vj-db
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  api:
    container_name: vj-api
    image: ghcr.io/bolinocroustibat/vj-api:${TAG:-latest}
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Application settings
      - ENVIRONMENT=${ENVIRONMENT:-unknown}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

      # Django settings
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

      # Database settings
      - POSTGRES_DB=${POSTGRES_DB}

      # CORS settings
      - CORS_ORIGIN_ALLOW_ALL=${CORS_ORIGIN_ALLOW_ALL}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

      # Nginx proxy settings
      - SECURE_PROXY_SSL_HEADER=${SECURE_PROXY_SSL_HEADER}

  frontend:
    container_name: vj-frontend
    image: vj-frontend:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-4173}:4173"
    depends_on:
      - api
    environment:
      # Frontend application settings
      - VITE_NEW_VIDEO_REQUEST_DELAY=${FRONTEND_NEW_VIDEO_REQUEST_DELAY:-8}
      - VITE_VIDEO_SWITCH_DELAY=${FRONTEND_VIDEO_SWITCH_DELAY:-2}
      - VITE_YOUTUBE_THEMES=${FRONTEND_YOUTUBE_THEMES:-""}
      - VITE_DEBUG=${DEBUG:-false}

      # Visual effects settings
      - VITE_VHS_EFFECT=${FRONTEND_VHS_EFFECT:-true}
      - VITE_GRAYSCALE_FILTER=${FRONTEND_GRAYSCALE_FILTER:-true}

      # Beat detection settings
      - VITE_BEAT_DETECTION_ENERGY_THRESHOLD=${FRONTEND_BEAT_DETECTION_ENERGY_THRESHOLD:-1000}
      - VITE_BEAT_DETECTION_BASS_THRESHOLD=${FRONTEND_BEAT_DETECTION_BASS_THRESHOLD:-300}
      - VITE_BEAT_DETECTION_BEAT_COOLDOWN=${FRONTEND_BEAT_DETECTION_BEAT_COOLDOWN:-300}
      - VITE_BEAT_DETECTION_CONFIDENCE_THRESHOLD=${FRONTEND_BEAT_DETECTION_CONFIDENCE_THRESHOLD:-0.99}

volumes:
  postgres_data:
  static_volume:
