[tool.poetry]
name = "vj-api"
version = "0.1.0"
description = "Provides a random YouTube video ID according to an optional given theme, and store cached YouTube IDs in a DB for later usage without depleting the YouTube API quota."
authors = ["Adrien Carpentier <moi@adriencarpentier.com>"]

[tool.poetry.dependencies]
python = "^3.7"
colorlog = "^5.0.1"
Django = "^3.2.3"
django-ninja = "^0.12.3"
django-cors-headers = "^3.7.0"
gunicorn = "^20.1.0"
PyMySQL = "^1.0.2"
requests = "^2.25.1"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
