[project]
name = "vj-api"
version = "1.0.21"
description = "Provides a random YouTube video ID according to an optional given theme, and store cached YouTube IDs in a DB for later usage without depleting the YouTube API quota."
authors = [{ name = "Adrien Carpentier", email = "me@adriencarpentier.com" }]
dependencies = [
    "colorlog>=6.9.0",
    "django>=5.2.6",
    "django-cors-headers>=4.8.0",
    "django-shinobi>=1.4.0",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "langdetect>=1.0.9",
    "nltk>=3.9.1",
    "orjson>=3.11.3",
    "psycopg-binary>=3.2.10",
    "psycopg>=3.2.10",
    "sentry-sdk>=2.37.0",
    "uvicorn>=0.35.0",
]
requires-python = ">=3.11,<3.15"
license = { text = "MIT" }
readme = "README.md"

[project.urls]
homepage = "https://vj.adriencarpentier.com/api"

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]

[tool.ruff]
line-length = 100
lint = { extend-select = ["ASYNC", "I", "PTH"] }
